### ISSUE TITLE
Limitation to images which size along each dimension has only 2,3, and 5 as prime factors

### ISSUE THREAD

**Issue by fbudin69500** [InsightSoftwareConsortium/ITKMontage#10]
When using `itkPhaseCorrelationImageRegistration`, for example with the example that is implemented, one is restricted to process images which size along each dimension has only 2,3, and 5 as prime factors. This is the case when using the VNL implementation of the FFT transform in ITK, and not the case when using the FFTW implementation, but the latter has license restriction. The filter should automatically pad the input, or preprocess the image such that the user can input image of any size.

**Comment by thewtex** [comment]
This is addressed in #15
