### ISSUE TITLE
Parsing Fiji File will cause crash if not on native platform

### ISSUE THREAD

**Issue by imikejackson** [InsightSoftwareConsortium/ITKMontage#103]
The parsing code uses std::readline() which is not cross platform compatible. The issue is that I write a Fiji file on Windows and it has CRLF as the line endings. Then I try to read it on macOS or Linux and the code will crash because readline() is looking for CR instead of CRLF that the file has.

Cross platform specific codes should be written to do the parsing instead of std::readline(). Every platform has "\n" so break the text using that, then strip off the '\r' character if any.

**Comment by dzenanz** [comment]
Didn't [4df8755](https://github.com/InsightSoftwareConsortium/ITKMontage/commit/4df8755f8dc5720971121e7237d296f4529072f9) fix it?

**Comment by dzenanz** [comment]
Fixed by #106.
