### ISSUE TITLE
Support different padding methods

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKMontage#12]
- zero pad
- mirror pad
- mirror pad with exponential decay

**Comment by dzenanz** [comment]
Support for mirror pad with exponential decay is in this [patch](http://review.source.kitware.com/#/c/23295/).

**Comment by dzenanz** [comment]
Mirror padding with exponential decay works better in the synthetic test than ordinary mirror padding (zero versus one test failure).
