### ISSUE TITLE
enum issues

### ISSUE THREAD

**Issue by csgerf** [InsightSoftwareConsortium/ITKMontage#155]
I had some issues using the tile merge filter in itkTileMontage now that the optimizer and padding method enums were moved to own class. I just switched the set macro for the peak interpolation method to itkSetEnumMacro and some other small changes in itkTileMontage.h

`  
  /** Set/Get the peak interpolation method. */
  itkSetEnumMacro(PeakInterpolationMethod, MaxPhaseCorrelationOptimizerEnums::PeakInterpolationMethod);
  itkGetConstMacro(PeakInterpolationMethod, MaxPhaseCorrelationOptimizerEnums::PeakInterpolationMethod);

  typename MaxPhaseCorrelationOptimizerEnums::PeakInterpolationMethod m_PeakInterpolationMethod =
    MaxPhaseCorrelationOptimizerEnums::PeakInterpolationMethod::Parabolic;`

**Comment by dzenanz** [comment]
Enums are being worked on, see [PR 146](https://github.com/InsightSoftwareConsortium/ITKMontage/pull/146).

**Comment by thewtex** [comment]
Enum's are now improved for ITK 5.1 and simplified. They are now in `itkPhaseCorrelationOptimizer.h`
