### ISSUE TITLE
Please tag the repo with the commit that corresponds to ITK 5.1.0

### ISSUE THREAD

**Issue by imikejackson** [InsightSoftwareConsortium/ITKMontage#170]

**Comment by thewtex** [comment]
@imikejackson when ITK 5.1.0 was released, this repo was at 2e7000149dd615dfb65d0664ec41a4026b95df11. However, `master` is tested against 5.1.0 is recommended over 2e7000149dd615dfb65d0664ec41a4026b95df11. Do you still want 2e7000149dd615dfb65d0664ec41a4026b95df11 tagged?

**Comment by dzenanz** [comment]
@imikejackson:
> I was trying to do a release of DREAM3D and now I’m getting compile errors because I am using ITK 5.1 release but master from Montage and TotalVariation.

**Comment by dzenanz** [comment]
It would be good to know which errors exactly, because current master should work well with ITK 5.1.0.

**Comment by dzenanz** [comment]
Closing this outdated issue.
