### ISSUE TITLE
Specification of TileConfiguration documentation

### ISSUE THREAD

**Issue by PRNicovich** [InsightSoftwareConsortium/ITKMontage#190]
I am working on implementing my own Python functions using the ITKMontage functions.  Getting stuck on the required configuration for TileConfiguration.  I see that issue #189 has some notes on this, but no explicit declaration of the format requirements.  I ask because I am struggling to generate a TileConfiguration.txt file for a straightforward set of my own data.  While having the contents as:

```# Define the number of dimensions we are working on
dim = 2

# Define the image coordinates
matlAreaAccumulation_A01_G002_0001_projection.tif; ; (0, 0)
matlAreaAccumulation_A01_G002_0002_projection.tif; ; (62, 60)
matlAreaAccumulation_A01_G002_0004_projection.tif; ; (0, 60)
matlAreaAccumulation_A01_G002_0003_projection.tif; ; (60, 0)
```

will successfully parse with ```stage_tiles.Parse(str(input_path / inputFileName))```, changing the file order to:

```# Define the number of dimensions we are working on
dim = 2

# Define the image coordinates
matlAreaAccumulation_A01_G002_0001_projection.tif; ; (0, 0)
matlAreaAccumulation_A01_G002_0004_projection.tif; ; (0, 60)
matlAreaAccumulation_A01_G002_0002_projection.tif; ; (62, 60)
matlAreaAccumulation_A01_G002_0003_projection.tif; ; (60, 0)
```

or to 

```# Define the number of dimensions we are working on
dim = 2

# Define the image coordinates
matlAreaAccumulation_A01_G002_0001_projection.tif; ; (0, 0)
matlAreaAccumulation_A01_G002_0004_projection.tif; ; (0, 60)
matlAreaAccumulation_A01_G002_0003_projection.tif; ; (60, 0)
matlAreaAccumulation_A01_G002_0002_projection.tif; ; (62, 60)
```

(only changing order of lines) yields a file that will not successfully parse.  Would it be possible to detail the requirements for tile position and/or this file format?

**Comment by PRNicovich** [comment]
Continuing, this parses fine:
```
# Define the number of dimensions we are working on
dim = 2

# Define the image coordinates
matlAreaAccumulation_A01_G002_0001_projection.tif; ; (0, 0)
matlAreaAccumulation_A01_G002_0002_projection.tif; ; (60, 0)
matlAreaAccumulation_A01_G002_0004_projection.tif; ; (0, 60)
matlAreaAccumulation_A01_G002_0003_projection.tif; ; (60, 60)
```

while this:

```
# Define the number of dimensions we are working on
dim = 2

# Define the image coordinates
matlAreaAccumulation_A01_G002_0001_projection.tif; ; (0, 0)
matlAreaAccumulation_A01_G002_0002_projection.tif; ; (60, 0)

matlAreaAccumulation_A01_G002_0003_projection.tif; ; (60, 60)
matlAreaAccumulation_A01_G002_0004_projection.tif; ; (0, 60)
```

 yields the error:

```
ITK ERROR: Axis sizes: [2, 1] current index: [0, 1]. We have reached the end along axis 1
Index along axis 0 is 0, but it should be 1
```

**Comment by dzenanz** [comment]
The coordinates should increase along X axis first, then Y axis, then (if present) Z axis. Of all the combinations you quoted above, I think only this one will produce the desired montage:
```text
# Define the number of dimensions we are working on
dim = 2

# Define the image coordinates
matlAreaAccumulation_A01_G002_0001_projection.tif; ; (0, 0)
matlAreaAccumulation_A01_G002_0002_projection.tif; ; (60, 0)
matlAreaAccumulation_A01_G002_0004_projection.tif; ; (0, 60)
matlAreaAccumulation_A01_G002_0003_projection.tif; ; (60, 60)
```

**Comment by dzenanz** [comment]
Where should this be documented?

**Comment by PRNicovich** [comment]
Happy to provide a working + annotated example script to illustrate the requirements for setting this tool up for you own use.  When this error is avoided it works well so I think we'll have something useful with your help to get around this formatting issue.


Unfortuately sorting rows in order of coordinate dimension does not seem to solve the issue.  This TileConfiguration.txt file:

```
# Define the number of dimensions
dim = 2

# Image coordinates
KB0004_1_10A_RolonyVis_A01_G001_0001_projection.tif;;(0,0)
KB0004_1_10A_RolonyVis_A01_G001_0004_projection.tif;;(0,972)
KB0004_1_10A_RolonyVis_A01_G001_0002_projection.tif;;(972,0)
KB0004_1_10A_RolonyVis_A01_G001_0003_projection.tif;;(972,972)
```

Yields this error on parsing:

```

```

  File "C:\Users\rusty\Documents\Python\OIRFiles\itkRegAndMontage.py", line 33, in parseStageTiles
    stage_tiles.Parse(filePath)

RuntimeError: ..\..\..\include\itkTileConfiguration.h:246:
ITK ERROR: Axis sizes: [1, 1], but we reached index 1. Violation along axis 0
```

The 'unsorted' raw order for tiles:

```
# Define the number of dimensions
dim = 2

# Image coordinates
KB0004_1_10A_RolonyVis_A01_G001_0001_projection.tif;;(1446,-972)
KB0004_1_10A_RolonyVis_A01_G001_0002_projection.tif;;(2419,-972)
KB0004_1_10A_RolonyVis_A01_G001_0003_projection.tif;;(2419,0)
KB0004_1_10A_RolonyVis_A01_G001_0004_projection.tif;;(1446,0)
```
Yields similar error:

```
RuntimeError: ..\..\..\include\itkTileConfiguration.h:231:
ITK ERROR: Axis sizes: [2, 1] current index: [0, 1]. We have reached the end along axis 1
Index along axis 0 is 0, but it should be 1
```

Any suggestions for this issue?

**Comment by dzenanz** [comment]
X-axis should increase first, so this should work:
```text
# Define the number of dimensions
dim = 2

# Image coordinates
KB0004_1_10A_RolonyVis_A01_G001_0001_projection.tif;;(0,0)
KB0004_1_10A_RolonyVis_A01_G001_0002_projection.tif;;(972,0)
KB0004_1_10A_RolonyVis_A01_G001_0004_projection.tif;;(0,972)
KB0004_1_10A_RolonyVis_A01_G001_0003_projection.tif;;(972,972)
```
the order is:
```text
first: x=0, y=0
second: x=something, y=0
third: x=0, y=something
last: x=something, y=something
```
The second example should be:
```text
# Define the number of dimensions
dim = 2

# Image coordinates
KB0004_1_10A_RolonyVis_A01_G001_0001_projection.tif;;(1446,-972)
KB0004_1_10A_RolonyVis_A01_G001_0002_projection.tif;;(2419,-972)
KB0004_1_10A_RolonyVis_A01_G001_0004_projection.tif;;(1446,0)
KB0004_1_10A_RolonyVis_A01_G001_0003_projection.tif;;(2419,0)
```

**Comment by dzenanz** [comment]
You could take a look at some example data, e.g.:
https://github.com/InsightSoftwareConsortium/ITKMontage/blob/master/test/Input/MNML_3_200x_701/TileConfiguration.txt

And tiles don't need to be exactly on a grid, as in this example:
https://github.com/InsightSoftwareConsortium/ITKMontage/blob/master/test/Input/MNML_3_200x_701/TileConfiguration.registered.txt

You can find more examples in the test data inputs:
https://github.com/InsightSoftwareConsortium/ITKMontage/tree/master/test/Input

**Comment by PRNicovich** [comment]
Thanks! I think I've got it.  The coordinates need to appear sorted in (Z)YX column order.  This example uses pandas to make a dataframe with what I believe has the proper sorting order:

```
import pandas as pd

def sortITKTileConfig(df):
    
    '''
    Parameters:
        df - dataframe
            Should have format roughly following N x [name, xval, yval, zval]
            for N files and N rows in dataframe
            
    Returns
        df - dataframe
        Sorted in ZYX order
    
    '''
    
    # Get column labels in (Z)YX order:
    colNames = [x for x in df.columns][::-1] 
    
    df = df.sort_values(colNames) 
        
    return df

    
def main(dFrame):
    
    print(sortITKTileConfig(dFrame))
    
if __name__ == "__main__":
    
        dFrame = pd.DataFrame([{'name' : 'green.png', 
                            'xVal' : 100, 
                            'yVal' : 0, 
                            'zVal' : 20},
                           {'name' : 'red.png', 
                            'xVal' : 100, 
                            'yVal' : 99, 
                            'zVal' : 20},
                           {'name' : 'blue.png', 
                            'xVal' : 22, 
                            'yVal' : 95, 
                            'zVal' : 10},
                           {'name' : 'cyan.png', 
                            'xVal' : 0, 
                            'yVal' : 100, 
                            'zVal' : 10},
                           {'name' : 'magenta.png', 
                            'xVal' : 100, 
                            'yVal' : 100, 
                            'zVal' : 10}])
        
        
        main(dFrame)
```

With this included in my code I can reliably get TileConfiguration.txt files that parse as expected.

**Comment by dzenanz** [comment]
That might not work with tiles which are not exactly on a grid, e.g.:
https://github.com/InsightSoftwareConsortium/ITKMontage/blob/master/test/Input/MNML_3_200x_701/TileConfiguration.registered.txt

**Comment by AcidLeroy** [comment]
@dzenanz I assume that the origin is in the top-left corner? 

<img width="241" alt="image" src="https://user-images.githubusercontent.com/249048/161776617-1803457a-8091-4f2d-9c90-7fba99605c77.png">

**Comment by dzenanz** [comment]
Yes, origin is top-left.

**Comment by dzenanz** [comment]
Reopen the issue if there are further details.
