### ISSUE TITLE
How to compile this module with cmake-gui in win10?

### ISSUE THREAD

**Issue by Hubrt-Zhu** [InsightSoftwareConsortium/ITKMontage#193]
![微信截图_20211202111704](https://user-images.githubusercontent.com/49428796/144351602-a5fe441c-3b90-4608-a612-af83ae5d2371.png)

 After reading your paper, I am very interested in the software library.  However, I am sorry that I have never used ITK.
I want to compile ITK and ITKMontage in cmake-gui in win10. I have downloaded ITK and Montage, but Montage is not available after compiling. I don't know how to set Module_Montage:BOOL=ON.
Can you give me some help and advice? Thank you very much.
![image](https://user-images.githubusercontent.com/49428796/144352294-84c96b48-2be2-4f26-ae4f-8cb3fbce2c46.png)

**Comment by dzenanz** [comment]
You need to enable the Advanced options. When doing that, it is also advisable to enable option grouping. If that is not enough, you should reduce `ITK_MINIMUM_COMPLIANCE_LEVEL` to show more remote modules.

**Comment by Hubrt-Zhu** [comment]
It's so kind of you. Thanks for your help, I have successfully compiled it. Thank you.
