### ISSUE TITLE
How to hide the shadow between 2 stitched tiles

### ISSUE THREAD

**Issue by zhusihan-python** [InsightSoftwareConsortium/ITKMontage#196]
hello, im running the sample replaced the origin data with my local tiles
environment: windows 10 python 3.9.0 itk-montage 0.7.3
![image](https://user-images.githubusercontent.com/23504604/149058303-ab9b4e22-88e5-4c56-a7ee-c996371f1142.png)
the result seems good yet there are shadow between each tiles, is there any param in TileMergeImageFilter to disable the shadow
or any documentation about this, can't find related part in https://itk.org/Doxygen/html/index.html or ItkSoftwareGuide
![image](https://user-images.githubusercontent.com/23504604/149058377-271c75b2-5aed-498e-b542-a149c151c76f.png)
Thanks

**Comment by zhusihan-python** [comment]
i found the shadow is related to padding method, when GetPaddingMethod return 2 its like above,
after SetPaddingMethod(1), the shadow shape changed
![28c8870522ad4dd2027f7fa4ded014f](https://user-images.githubusercontent.com/23504604/149080165-ef01f8e2-7bab-45fd-930d-cd5a207fed28.png)
but still can find out how to eliminate it

**Comment by dzenanz** [comment]
This was also posted to the forum. Crosslink: https://discourse.itk.org/t/how-to-hide-the-shadow-between-2-fused-blend-tiles/4725.

**Comment by zhusihan-python** [comment]
sor for didn't upload the code, here it is, i did't change the sample code

```import sys
import os
import itk
from pathlib import Path

if len(sys.argv) < 4:
  print(f"Usage: {sys.argv[0]} <directoryWithInputTiles> <outputDirectory> <outputFilename>")
  sys.exit(1)

input_path = Path(sys.argv[1])
output_path = Path(sys.argv[2])
out_file = Path(sys.argv[3])
if not out_file.is_absolute():
  out_file = (output_path / out_file).resolve()


dimension = 2

stage_tiles = itk.TileConfiguration[dimension]()
stage_tiles.Parse(str(input_path / "TileConfiguration.txt"))

color_images = [] # for mosaic creation
grayscale_images = [] # for registration
for t in range(stage_tiles.LinearSize()):
  origin = stage_tiles.GetTile(t).GetPosition()
  filename = str(input_path / stage_tiles.GetTile(t).GetFileName())
  image = itk.imread(filename)
  spacing = image.GetSpacing()

  for d in range(dimension):
    origin[d] *= spacing[d]

  image.SetOrigin(origin)
  color_images.append(image)

  image = itk.imread(filename, itk.F) # read as grayscale
  image.SetOrigin(origin)
  grayscale_images.append(image)

montage = itk.TileMontage[type(grayscale_images[0]), itk.F].New()
montage.SetMontageSize(stage_tiles.GetAxisSizes())
for t in range(stage_tiles.LinearSize()):
  montage.SetInputTile(t, grayscale_images[t])

print("Computing tile registration transforms")
montage.Update()

print("Writing tile transforms")
actual_tiles = stage_tiles # we will update it later
for t in range(stage_tiles.LinearSize()):
  index = stage_tiles.LinearIndexToNDIndex(t)
  regTr = montage.GetOutputTransform(index)
  tile = stage_tiles.GetTile(t)
  itk.transformwrite([regTr], str(output_path / (tile.GetFileName() + ".tfm")))

  pos = tile.GetPosition()
  for d in range(dimension):
    pos[d] -= regTr.GetOffset()[d] / spacing[d]
  tile.SetPosition(pos)
  actual_tiles.SetTile(t, tile)
actual_tiles.Write(str(output_path / "TileConfiguration.registered.txt"))

print("Producing the mosaic")
resampleF = itk.TileMergeImageFilter[type(color_images[0])].New()
resampleF.SetMontageSize(stage_tiles.GetAxisSizes())
for t in range(stage_tiles.LinearSize()):
  resampleF.SetInputTile(t, color_images[t])
  index = stage_tiles.LinearIndexToNDIndex(t)
  resampleF.SetTileTransform(index, montage.GetOutputTransform(index))
resampleF.Update()
itk.imwrite(resampleF.GetOutput(), str(out_file))
print("Resampling complete")
```
the configure file
```
# Tile coordinates are in index space, not physical space
dim = 2

000_019.jpg;;(0, 0)
000_018.jpg;;(0, 1444)
000_017.jpg;;(0, 2888)
000_016.jpg;;(0, 4332)
000_015.jpg;;(0, 5776)
```
logs

Template itk::Image<std::complex<double>,2>
 already defined as <class 'itk.itkImagePython.itkImageCD2'>
 is redefined as {cl}
Warning: template already defined 'itk::Image<std::complex<double>,2>'
Template std::vector<itk::Image<std::complex<double>,2>>
 already defined as <class 'itk.itkImagePython.vectoritkImageCD2'>
 is redefined as {cl}
Template itk::Image<std::complex<double>,3>
 already defined as <class 'itk.itkImagePython.itkImageCD3'>
 is redefined as {cl}
Warning: template already defined 'itk::Image<std::complex<double>,3>'
Template std::vector<itk::Image<std::complex<double>,3>>
 already defined as <class 'itk.itkImagePython.vectoritkImageCD3'>
 is redefined as {cl}
Template itk::Image<std::complex<double>,4>
 already defined as <class 'itk.itkImagePython.itkImageCD4'>
 is redefined as {cl}
Warning: template already defined 'itk::Image<std::complex<double>,4>'
Template std::vector<itk::Image<std::complex<double>,4>>
 already defined as <class 'itk.itkImagePython.vectoritkImageCD4'>
 is redefined as {cl}
Template itk::ImageSource<itk::Image<std::complex<double>,2>>
 already defined as <class 'itk.itkImageSourcePython.itkImageSourceICD2'>
 is redefined as {cl}
Template itk::ImageSource<itk::Image<std::complex<double>,3>>
 already defined as <class 'itk.itkImageSourcePython.itkImageSourceICD3'>
 is redefined as {cl}
Template itk::ImageSource<itk::Image<std::complex<double>,4>>
 already defined as <class 'itk.itkImageSourcePython.itkImageSourceICD4'>
 is redefined as {cl}
Template itk::ImageToImageFilter<itk::Image<std::complex<double>,2>,itk::Image<std::complex<double>,2>>
 already defined as <class 'itk.itkImageToImageFilterBPython.itkImageToImageFilterICD2ICD2'>
 is redefined as {cl}
Template itk::ImageToImageFilter<itk::Image<std::complex<double>,3>,itk::Image<std::complex<double>,3>>
 already defined as <class 'itk.itkImageToImageFilterBPython.itkImageToImageFilterICD3ICD3'>
 is redefined as {cl}
Template itk::ImageToImageFilter<itk::Image<std::complex<double>,4>,itk::Image<std::complex<double>,4>>
 already defined as <class 'itk.itkImageToImageFilterBPython.itkImageToImageFilterICD4ICD4'>
 is redefined as {cl}
Computing tile registration transforms

Iteration 1  Writing tile transforms
Producing the mosaic
Resampling complete

**Comment by zhusihan-python** [comment]
test imgs
[SampleData_Micro.zip](https://github.com/InsightSoftwareConsortium/ITKMontage/files/7856949/SampleData_Micro.zip)

**Comment by zhusihan-python** [comment]
[TileConfiguration.txt](https://github.com/InsightSoftwareConsortium/ITKMontage/files/7856961/TileConfiguration.txt)

**Comment by zhusihan-python** [comment]
i don't know how to change to 16 bits, i will try to change it and run the cpp example tommorrow, then update the result here, i ran the python example with the \SampleData_CMUrun2, it turns out all as expectation. thank you sir

**Comment by dzenanz** [comment]
Changing [line 44](https://github.com/InsightSoftwareConsortium/ITKMontage/blob/v0.7.3/examples/SimpleMontage.py#L44) to `image = itk.imread(filename, itk.US)`, and invoking with `python ./SimpleMontage.py . . montage.png` results in a grayscale image without the gray rectangles (see below). Changing it to `image = itk.imread(filename, itk.RGBUS)` should work, but you need to build ITK from source, and enable `ITK_WRAP_rgb_unsigned_short` during configuration stage.

If you want the output to be 8-bit, add a [RescaleIntensity](https://itk.org/Doxygen/html/classitk_1_1RescaleIntensityImageFilter.html) filter at the end. I rescaled this image using Slicer.
![montage](https://user-images.githubusercontent.com/1792121/149209412-19369481-77c1-430a-9a63-e13a693a858a.jpg)

**Comment by zhusihan-python** [comment]
> Changing [line 44](https://github.com/InsightSoftwareConsortium/ITKMontage/blob/v0.7.3/examples/SimpleMontage.py#L44) to `image = itk.imread(filename, itk.US)`, and invoking with `python ./SimpleMontage.py . . montage.png` results in a grayscale image without the gray rectangles (see below). Changing it to `image = itk.imread(filename, itk.RGBUS)` should work, but you need to build ITK from source, and enable `ITK_WRAP_rgb_unsigned_short` during configuration stage.
> 
> If you want the output to be 8-bit, add a [RescaleIntensity](https://itk.org/Doxygen/html/classitk_1_1RescaleIntensityImageFilter.html) filter at the end. I rescaled this image using Slicer. ![montage](https://user-images.githubusercontent.com/1792121/149209412-19369481-77c1-430a-9a63-e13a693a858a.jpg)

hello Mr dzenanz
    i build SimpleITK with vs 17 2022, cmake 3.22.1 following this [instruction ](https://simpleitk.readthedocs.io/en/master/buildingWindows.html)
    when fixed several errors, it succeed. yet when i want to install the python wrap, found that no wrap files generated.
    here is my cmake config
    
![image](https://user-images.githubusercontent.com/23504604/149293894-734f01d0-36a0-42d6-ae2f-3dcbd857f1b4.png)
![image](https://user-images.githubusercontent.com/23504604/149294087-578bbc22-67ad-4fb7-a036-884800e303d3.png)
![image](https://user-images.githubusercontent.com/23504604/149294144-2bc0f6fd-6bb6-49f9-af9f-90f9c8209f02.png)
build results
![image](https://user-images.githubusercontent.com/23504604/149294339-0fe12666-f139-4ff4-9f97-75ec03dc10fe.png)
build log
```
Found PythonInterp: D:/softwares/py39/python.exe (found version "3.9.9") 
Found PythonLibs: D:/softwares/py39/libs/python39.lib (found suitable exact version "3.9.9") 
Could NOT find Tclsh (missing: TCL_TCLSH) 
Found the following C# .NET versions: v4.0.30319, v3.5, v2.0.50727
Found CSharp: .NET  
Passing variable "ITK_BUILD_DEFAULT_MODULES=ON" to ITK external project.
Passing variable "ITK_DEFAULT_THREADER=Platform" to ITK external project.
Passing variable "ITK_GIT_REPOSITORY=https://github.com/InsightSoftwareConsortium/ITK.git" to ITK external project.
Passing variable "ITK_GIT_TAG=af32a779c4586304e52ddc27eb81656b949c9eeb" to ITK external project.
Passing variable "ITK_USE_64BITS_IDS=ON" to ITK external project.
Passing variable "ITK_WRAP_rgb_unsigned_short=ON" to ITK external project.
Passing variable "Module_ITKIOTransformMINC=ON" to ITK external project.
Passing variable "Module_ITKReview=ON" to ITK external project.
Passing variable "Module_SimpleITKFilters=ON" to ITK external project.
Passing variable "SITK_CMAKE_MINIMUM_REQUIRED_VERSION=3.16.3" to SimpleITK external project.
Passing variable "SITK_CMAKE_POLICY_VERSION=3.16.3" to SimpleITK external project.
Passing variable "SimpleITK_GIT_PROTOCOL=https" to SimpleITK external project.
Passing variable "SimpleITK_LUA_EXECUTABLE=E:/projects/SimpleITK-build-new/Lua/bin/lua" to SimpleITK external project.
Passing variable "SimpleITK_MAX_DIMENSION=5" to SimpleITK external project.
Configuring done
Generating done
```
is there anything i was missing

**Comment by dzenanz** [comment]
SimpleITK should pass `Module_Montage=ON` to ITK, in addition to other stuff like `Passing variable "ITK_WRAP_rgb_unsigned_short=ON" to ITK external project.`

**Comment by zhusihan-python** [comment]
finally i compiled itk success, the build output is really huge around 12 GB, cost more than 4 hrs by my intel i5 10400 cpu i think
I get the itk package in build\Wrapping\Generators\Python\
![image](https://user-images.githubusercontent.com/23504604/149443366-49980008-3f5d-496d-acc0-79a3194cf33e.png)
run ctest -R, only 9% tests passed, the rest test case didn't run.
![image](https://user-images.githubusercontent.com/23504604/149445893-f5a81ab2-dbe0-4e8f-94fe-9a30ea678797.png)
test the package with my tiles:
as there is no setup.py file to install, so i copy the itk package to python Lib\site-packages\ replaced the old one
running to this line get error "module 'itk' has no attribute 'RGBUS'"
`image = itk.imread(filename, itk.RGBUS)`
i checked the types.py, it didn't define RGBUS like before
![image](https://user-images.githubusercontent.com/23504604/149443978-c25b8f15-3c17-4476-b6ef-51528cdad309.png)
i checked my cmake configure, the ITK_WRAP_rgb_unsigned_short is set to ON
![image](https://user-images.githubusercontent.com/23504604/149446460-2bf4fb61-889e-4f61-9285-02a1d0362c3f.png)
and I tried this version image = itk.imread(filename, itk.US) didn't get the grey img like yours,  either with itk default nor itk compiled by myself, its a black one in my computer. 
![image](https://user-images.githubusercontent.com/23504604/149444821-863460de-4a9d-44af-80a3-7e9ea3cbf291.png)

the data and configure file are all the same like above.

**Comment by dzenanz** [comment]
> ctest -R

You need to run `ctest -C Release`, or `ctest -C Release -j3` (depending on your build configuration).

To use the just-built version of ITK, you need to remove all traces of ITK from your Python installation and copy WrapITK.pth file into site-packages. On my computer it is in `C:\Program Files\Python37\Lib\site-packages\WrapITK.pth` and has the following content:
```text
# Python pth file to add itk package path to sys.path
# for itk version "5.3.0"
C:/Dev/ITK-py/Wrapping/Generators/Python
```
The montage image you got is likely correct, but it uses only the lower 8 bits of the 16-bit intensity range. You need a good viewer to see it properly. [Slicer](https://download.slicer.org/) works.

Alternatively, you could add a cast step at the end. Replace [line 92](https://github.com/InsightSoftwareConsortium/ITKMontage/blob/v0.7.3/examples/SimpleMontage.py#L92) by
```py
cast_image = resampleF.GetOutput().astype(itk.UC)
itk.imwrite(cast_image, str(out_file))
```

**Comment by zhusihan-python** [comment]
thank you sir, i create a new virtual python environment and put the WrapITK.pth.
`cast_image = resampleF.GetOutput().astype(itk.UC)`
it worked!
![image](https://user-images.githubusercontent.com/23504604/149556658-2e3997c9-1ccc-4e07-b647-6ff7be8cd304.png)
`image = itk.imread(filename, itk.RGBUS)`
still didn't work, the itk types didn't have RGBUS
i think itk need to be rebuilt to get the RGBUS, ITK_WRAP_rgb_unsigned_short=ON not enough i guess, and i tried ITK_WRAP_rgba_unsigned_short=ON, the types.py didn't have RGBAUS too, what else setting should i set cmake to get it
or can i add RGBUS in types.py by myself, if so, what numpy types should be set accordingly
![image](https://user-images.githubusercontent.com/23504604/149558710-dd382eb4-dbbb-4f84-9231-7556bf162f05.png)

**Comment by dzenanz** [comment]
What is the error when you try `image = itk.imread(filename, itk.RGBUS)`?

**Comment by dzenanz** [comment]
You should not need `ITK_WRAP_rgba_unsigned_short`, as `.jpg` files do not have an alpha channel.

**Comment by zhusihan-python** [comment]
> What is the error when you try `image = itk.imread(filename, itk.RGBUS)`?

"module 'itk' has no attribute 'RGBUS'"
as the itk/support/types.py didn't definite RGBUS

**Comment by zhusihan-python** [comment]
> You should not need `ITK_WRAP_rgba_unsigned_short`, as `.jpg` files do not have an alpha channel.

yep. i mean that maybe set ITK_WRAP_rgb_unsigned_short=ON will not makes RGBUS defined in types.py
same as set ITK_WRAP_rgba_unsigned_short=ON will not makes RGBAUS defined in types.py
i guess the types are fixed 14 types in WrapBasicTypes.cmake, ITK_WRAP_rgb_unsigned_short is not able to get itk.RGBUS or not enough to 
![image](https://user-images.githubusercontent.com/23504604/149607404-78afc03d-28e6-4a2e-b6da-d8f9749e4dbe.png)

**Comment by dzenanz** [comment]
> set ITK_WRAP_rgb_unsigned_short=ON will not makes RGBUS defined in types.py

Could you submit this bug report to the [main repository](https://github.com/InsightSoftwareConsortium/ITK)?

What happens during configure stage if you add a `message("blah")` inside this `if`: https://github.com/InsightSoftwareConsortium/ITK/blob/v5.3rc03/Wrapping/WrapBasicTypes.cmake#L119-L121?

**Comment by zhusihan-python** [comment]
> message("blah")
the message is in output, it step into the if
![image](https://user-images.githubusercontent.com/23504604/149808782-d53b60ae-011c-4ed3-b9b2-75873388b51f.png)
i will try to build a release again to double check. if still not ok then report to main repo

**Comment by zhusihan-python** [comment]
main repo bug [issuse](https://github.com/InsightSoftwareConsortium/ITK/issues/3124) submitted

**Comment by dzenanz** [comment]
The issue was resolved. See https://github.com/InsightSoftwareConsortium/ITK/issues/3124 for the end of this discussion.
