### ISSUE TITLE
High-resolution 3D Stitching Parallelization

### ISSUE THREAD

**Issue by bsaldana-cajal** [InsightSoftwareConsortium/ITKMontage#201]
I am trying to stitch two large 3D images with >90% overlap using the SimpleMontage.py example script and am having memory/timeout issues at the montage.Update() stage. This script works perfectly with lower resolution versions of the same data.

I have already tried increasing the resources available (400GBs and 3hrs timeout duration) but continue having problems.
I have also tried montage.SetNumberOfWorkUnits(n_threads=64) and still get stuck at montage.Update().

Is there any way to parallelize any part of the stitching process to avoid these issues?

**Comment by dzenanz** [comment]
Parallelization is done on tiles. With just two tiles, there is not a lot of opportunity for parallelization, nor for reducing parallelism. Registration is done on the overlapping part of images, and you have pretty much the worst case here from memory consumption point of view: 2 tiles with 90% overlap.

What you could do is do the [registration](https://github.com/InsightSoftwareConsortium/ITKMontage/blob/master/examples/RefineMontage.cxx) on the lower resolution version of data, then do the [stitching](https://github.com/InsightSoftwareConsortium/ITKMontage/blob/master/examples/ResampleMontage.cxx) on full resolution data. If you run into memory issues there, you might want to enable [chunked processing](https://github.com/InsightSoftwareConsortium/ITKMontage/blob/v0.7.3/test/itkMontageTestHelper.hxx#L403-L414). Beware: not all image formats support streaming.

**Comment by bsaldana-cajal** [comment]
Thank you for your response @dzenanz! I'll give this a try for my two large tile stitching problem :)

I have also tried to stitch 20 high-resolution tiles with 10%-ish overlap and am also seeing memory/timeout issues. Is there a native way to parallelize this using itkMontage?

**Comment by dzenanz** [comment]
It is parallel by default. You might want to limit parallelism to reduce memory use. For example, define environment variable called `NSLOTS` and set its value to `2`.

**Comment by bsaldana-cajal** [comment]
Thank you!!
