### ISSUE TITLE
Feasibility of employing ITKMontage for MRI stitching 

### ISSUE THREAD

**Issue by jqmcginnis** [InsightSoftwareConsortium/ITKMontage#203]
Hi ITKMontage team,

I am seeking a tool for merging two acquired MRI stacks with overlap, that rescale the intensities and stitch the images (without losing the world coordinate space of the scanner). Having read the paper I am not 100% sure if this can be achieved using ITKMontage, perhaps you can indicate whether or not this is possible.

I am currently trying to use the `SimpleMontage.py` script, but do not know how to deal with the two MRI images w.r.t. the image coordinates, e.g. the creation of the `TileConfiguration.txt` file.
```
# Tile coordinates are in index space, not physical space
dim = 3

img1.nii.gz;;(0, 0, 0)
img2.nii.gz;;(X,Y,Z)
```
As the exact overlap and location are unknown, I cannot specify the overlapping voxels. Is there any way to address this?

**Comment by dzenanz** [comment]
You could use `itk::TileMergeImageFilter` directly, something like:
```py
resampleF = itk.TileMergeImageFilter[type(color_images[0])].New()
resampleF.SetMontageSize([1, 1, 2]])
resampleF.SetInputTile(0, image1)
resampleF.SetInputTile(1, image2)
resampleF.Update()
itk.imwrite(resampleF.GetOutput(), str(out_file))
```

**Comment by jqmcginnis** [comment]
Hi @dzenanz,

Thank you very much for the helpful answer. Just to confirm I understand this properly, do you recommend bypassing the loading of tiles all together?  i.e. skipping [start_of_section](https://github.com/InsightSoftwareConsortium/ITKMontage/blob/master/examples/SimpleMontage.py#L36) and [end of section](https://github.com/InsightSoftwareConsortium/ITKMontage/blob/master/examples/SimpleMontage.py#L82).

In the `SimpleMontage.py` the tiles are loaded using the origins obtained in the `TileConfiguration.txt`, then the coordinates are recomputed using the spacing and origin. As we load the images as NIFTIs, which directly use the affines for world coordinate computations in itk, I have the understanding that we would not have to compute the coordinates at all? I have the impression that itk would already know the coordinates, but I could be wrong of course!

Otherwise we could compute these as well, e.g.
```

color_images = [] # for mosaic creation
grayscale_images = [] # for registration

for t in range(len(input_files)):

  image = itk.imread(input_files[t])
  origin = image.GetOrigin()
  spacing = image.GetSpacing()

  # tile configurations are in pixel (index) coordinates
  # so we convert them into physical ones
  for d in range(dimension):
    origin[d] *= spacing[d]

  image.SetOrigin(origin)
  color_images.append(image)

  image = itk.imread(input_files[t], itk.F) # read as grayscale
  image.SetOrigin(origin)
  grayscale_images.append(image)
```
I've tried to run the script without the re-computation, which leads to a segmentation fault (difficult for me to debug). Unsure, if this is due to the missing coordinate transformation or other problems? :slightly_smiling_face:

**Comment by dzenanz** [comment]
> we would not have to compute the coordinates at all

I think so.

> segmentation fault

Setting transforms might be needed, even if they are identity.

We finished this module 2 years ago, and have only been maintaining it since. I don't remember all the details of how it works. And we did not exactly foresee your case when we wrote it.

**Comment by dzenanz** [comment]
Reopen the issue if there are further details.
