### ISSUE TITLE
How to stitch microscope images with python.

### ISSUE THREAD

**Issue by kuldeep203** [InsightSoftwareConsortium/ITKMontage#208]
i have 17x17 microscope images. i want to stitch all together but not getting how to do that. i installed ITKMontage with pip but after that not able to do anything.

**Comment by dzenanz** [comment]
If you need to do this just once, you are better off using end-user software such as [DREAM.3D](http://www.dream3d.io/) or [Image Stitching Plugin](https://imagej.net/plugins/image-stitching) for Fiji.

If you insist on using `ITKMontage` directly, you should construct `TileConfiguration.txt` similarly to the ones in test inputs (e.g. [S200](https://github.com/InsightSoftwareConsortium/ITKMontage/blob/master/test/Input/S200-6-C/TileConfiguration.txt)) and then use the [example script](https://github.com/InsightSoftwareConsortium/ITKMontage/blob/master/examples/SimpleMontage.py) to invoke the code.
