### ISSUE TITLE
is there a way to delete the image vectors after montage finish calculate in CompleteMontage.cxx

### ISSUE THREAD

**Issue by zhusihan-python** [InsightSoftwareConsortium/ITKMontage#209]
the oImages, sImages, bImages is no longer used after montage Update, i want to release the momory they occupied
```
montage->Update(); // calculate registration transforms
oImages.clear();
oImages.shrink_to_fit();
sImages.clear();
sImages.shrink_to_fit();
bImages.clear();
bImages.shrink_to_fit();
```
also i want to delete montage after resample Update
```
delete montage ;
delete resampleF;
```
yet the deconstruct funtion is protected, i change it to public, the program
will coredump, is there a better way to release memory that mid variables no longer used in CompleteMontage,
as i want to send the resample output to a matlab dll, my pc will be out of memory if not released before GetOutput

**Comment by dzenanz** [comment]
You could put the code into a code block, e.g.:
```cpp
ClassWhichAllocatesMemory var1;
// do stuff
someResult = var1.someMethod();
// now we no longer need var1
```
the usual solution:
```cpp
someResult;
{
  ClassWhichAllocatesMemory var1;
  // do stuff
  someResult = var1.someMethod();
} // when this block is closed, var1 goes out of scope and is deallocated
someResult.use();
```

But in this instance there are two more options:
```cpp
for (size_t t = 0; t < stageTiles.LinearSize(); t++)
{
  montage->SetInputTile(t, nullptr); // release montage's pointer to the image
}
```
This should get the images' reference counters down to zero, causing them to be deallocated.

But as variable `montage` is a pointer, this should have the same effect and is shorter: `montage = nullptr;`. It will cause the `montage` to be deallocated, along with its internal variables.

**Comment by dzenanz** [comment]
Reopen issues if there are further details.
