### ISSUE TITLE
Add Jupyter Notebooks to demonstrate usage

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKMontage#210]

**Comment by sebgoti** [comment]
Would it be possible to add one where it is shown how to do stitching on 3D data? Another idea, show how to do it for multidimensional data (TCYZX)

**Comment by dzenanz** [comment]
There are some 3D unit tests, e.g. this one:
https://github.com/InsightSoftwareConsortium/ITKMontage/blob/b1e41dd30c3411e403769d3bb5eb3e1502ec8d1f/test/CMakeLists.txt#L489-L523
You could use them for inspiration.

**Comment by sebgoti** [comment]
I was thinking more on the side of some python code besides the one example :D

**Comment by dzenanz** [comment]
The current python example might even work for 3D. You need to provide 3D version of `TileConfiguration.txt`.

**Comment by dzenanz** [comment]
Accomplished by 7015e4aee2942509a9cc46a2f4f7861b25f79725.
