### ISSUE TITLE
Tile placement requirement

### ISSUE THREAD

**Issue by ckolluru** [InsightSoftwareConsortium/ITKMontage#222]
Thanks for this work. I wanted to know if there is a requirement that the tiles inputted for stitching lay on a regular grid in space?

Can tiles collected at arbitrary locations (say 5 tiles instead of a 2x2 or 3x3 grid) be stitched with this software?

**Comment by dzenanz** [comment]
We don't have direct support for such a flexibility - every tile should have a valid image. There is nothing preventing you from creating one all-black properly sized image and passing it in instead of the missing tiles.

**Comment by ckolluru** [comment]
Got it, thanks.
