### ISSUE TITLE
How to modify the code

### ISSUE THREAD

**Issue by sssixty** [InsightSoftwareConsortium/ITKMontage#223]
I'm trying to modify the **DistanceFromEdge** function in **itkTileMergeImageFilter.hxx**. After finishing the modifications, how to update the corresponding function in the Python package? I think I should use setup.py to  rebuild the package, but I'm not sure of the specific steps.

**Comment by dzenanz** [comment]
Have you tried these [instructions](https://itkpythonpackage.readthedocs.io/en/latest/Build_ITK_Module_Python_packages.html)? Of course, you should skip "Upload to PyPI" step.

**Comment by sssixty** [comment]
Thanks!
