### ISSUE TITLE
Band-pass frequencies

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITKMontage#43]
Reduce high frequencies to reduce noise, and low frequencies to reduce influence of uneven illumination. Do it in Fourier space. Possibly ignore the highest frequencies entirely by cropping.

**Comment by thewtex** [comment]
Related:

https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Filtering/ImageFrequency/include/itkFrequencyBandImageFilter.h

https://github.com/KitwareMedical/ITKUltrasound/blob/master/include/itkButterworthBandpass1DFilterFunction.h

**Comment by dzenanz** [comment]
A fancier band-pass filtering (e.g. Butterworth) should be enabled when this is merged: https://github.com/InsightSoftwareConsortium/ITK/pull/149
