### ISSUE TITLE
Add as a remote module to ITK

### ISSUE THREAD

**Issue by jhlegarreta** [InsightSoftwareConsortium/ITKMontage#51]
@thewtex @dzenanz This seems to be a module the Luis started. I guess it should be added as a remote. You may have already planned to do so.

Let me know if only the `*.remote.cmake` file is missing and if I can help, or else, whether you are working for the module to pass all checks

**Comment by thewtex** [comment]
@jhlegarreta Thanks for bringing this up. The functionality is not quite there to be included as a remote module (and there is no documentation). But we should eventually add it as a remote module.

**Comment by jhlegarreta** [comment]
@thewtex OK, thanks for the note.

Let's wait until we are able to do some more work on the module to put everything in place then.

**Comment by jhlegarreta** [comment]
Closing: the module was added as a remote in the referenced PR.
